### ISSUE TITLE
OpenGL.error.NullFunctionError: Attempt to call an undefined function gluPerspective

### ISSUE THREAD

**Issue by JoarGjersund** [thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation#1]
I am running on Linux (Ubuntu). The window shows for a brief moment before it closes and this error appears:

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "pyteapot.py", line 188, in <module>
    main()
  File "pyteapot.py", line 21, in main
    resizewin(640, 480)
  File "pyteapot.py", line 52, in resizewin
    gluPerspective(45, 1.0*width/height, 0.1, 100.0)
  File "/usr/local/lib/python2.7/dist-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function gluPerspective, check for bool(gluPerspective) before calling

**Comment by JoarGjersund** [comment]
had to do apt-get install freeglut3 and freeglut3-dev.

**Comment by thecountoftuscany** [comment]
Closing the issue.
