### ISSUE TITLE
Which order to pass quaternions?

### ISSUE THREAD

**Issue by AsternA** [thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation#13]
Hey!

I have a dataset of IMU recordings with video and I want to verify that the quaternion outputs match the orientation I see on the video itself but I see no correlation between the video and the visualization for some reason.

I am trying to see if the sensor is outputting the wrong quaternion information (could be, using pretty low MAG, GYRO and ACCEL sample rate) but to be sure I need to know that the visualization is not wrong. 

I am passing QuatW QuatX QuatY and QuatZ. Is this the correct order?

Thanks

**Comment by AsternA** [comment]
going into the code I saw that it is in deed W X Y Z. 

Can close this issue

**Comment by thecountoftuscany** [comment]
Yes, also described in the readme
