### ISSUE TITLE
MPU9250 sensor fusion

### ISSUE THREAD

**Issue by KeepThisTicket** [thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation#3]
Where can I get find the code that generates the quaternion for the MPU9250 raw data ? Your sensor performance looks really good.

**Comment by thecountoftuscany** [comment]
I used the quaternionFilters.ino file from [this repo](https://github.com/kriswiner/MPU9250), which uses the Madgwick or the Mahony filters for sensor fusion. I don't exactly remember exactly which one among those two the gif in my readme corresponds to, but both of them had an almost identical performance.

**Comment by KeepThisTicket** [comment]
Awesome - thanks for the quick reply!
