### ISSUE TITLE
Quaternion calculation

### ISSUE THREAD

**Issue by lolodenimes** [thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation#4]
is the calculation correct?
On your code:
yaw   = math.atan2(2.0 * (q[1] * q[2] + q[0] * q[3]), q[0] * q[0] + q[1] * q[1] - q[2] * q[2] - q[3] * q[3])
pitch = -math.sin(2.0 * (q[1] * q[3] - q[0] * q[2]))
roll  = math.atan2(2.0 * (q[0] * q[1] + q[2] * q[3]), q[0] * q[0] - q[1] * q[1] - q[2] * q[2] + q[3] * q[3])
And on wikipedia for example:
yaw = atan2(2 * (q0 * q3 + q1 * q2), 1 - 2 * (q2 * q2 + q3 * q3));
pitch = asin( 2 * (q0 * q2 - q3 * q1));
roll = atan2(2 * (q0 * q1 + q2 * q3),1 - 2 * (q1 * q1 + q2 * q2));

**Comment by thecountoftuscany** [comment]
These forms are equivalent since the sum of squares of quaternions is 1 and sin() is an odd function. Refer [this page](https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Definition).
