### ISSUE TITLE
unable to initialize

### ISSUE THREAD

**Issue by 0xEDED93** [thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation#5]
besides, configuring serial quaternion mode, does anything else need to be done to  initialize the application?
I have also installed  PyOpenGL and pygame. When i run the app a white window comes up, it never gets to draw the real application

**Comment by thecountoftuscany** [comment]
PyOpenGL, pygame and PySerial (if receiving orientation data over serial) are the only requirements. Are you using any virtual environments (eg using venv or conda)? Are there any error messages in the terminal? Any tracebacks?

Also see if [this issue](https://github.com/thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation/issues/1) is relevant.

**Comment by thecountoftuscany** [comment]
Closing this for now as it's been more than a year since it was opened. But feel free to reopen if someone is still having this issue.

**Comment by DoubleF3lix** [comment]
I am having this issue. No errors, tracebacks, and all of the requirements are installed. The window immediately just doesn't respond.

**Comment by thecountoftuscany** [comment]
Hi @DoubleF3lix, have you checked the linked issue in [this comment](https://github.com/thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation/issues/5#issuecomment-878949135)?

**Comment by DoubleF3lix** [comment]
Pip says that it couldn't find a package with the name of "freeglut3" (windows 10)

**Comment by thecountoftuscany** [comment]
That is not a python package. Please install either OpenGL, GLUT or FreeGLUT for your OS from their website.

**Comment by RafigRzayev** [comment]
Can someone share what did you to make it to run on windows?

**Comment by thecountoftuscany** [comment]
Linking to https://github.com/thecountoftuscany/PyTeapot-Quaternion-Euler-cube-rotation/issues/11#issuecomment-1196272222 for instructions to make the program work on Windows.
